import * as React from "react";
import { useEffect } from "react";
import AboutMe from "./AboutMe";
import city from "../public/city.png";
import Footer from "./Footer";
import Head from "next/head";
import Image from "next/image";
import ImageSlider from "./ImageSlider";
import museum2 from "../public/museum2.png";
import Navbar from "./Navbar";
import needle2 from "../public/needle2.png";
import ScrollToTop from "react-scroll-to-top";
import woods2 from "../public/woods2.png";
import Skills from "./Skills";

export default function Home() {
  const slides = [
    {
      url: "/eats.mp4",
      title: "Eats",
      githubLink: "https://github.com/Ksalmeron1993/eats.git",
    },
    {
      url: "/carcar.png",
      title: "Car Services",
      githubLink: "https://github.com/Ksalmeron1993/carservices.git",
    },
    {
      url: "/movie.png",
      title: "MovieMania",
      githubLink: "https://github.com/Ksalmeron1993/MovieMania.git",
    },
   
  ];

  const containerStyles = {
    width: "500px",
    height: "280px",
    margin: "0 auto",
  };

  function reveal() {
    var reveals = document.querySelectorAll(".reveal");

    for (var i = 0; i < reveals.length; i++) {
      var windowHeight = window.innerHeight;
      var elementTop = reveals[i].getBoundingClientRect().top;
      var elementVisible = 150;

      if (elementTop < windowHeight - elementVisible) {
        reveals[i].classList.add("active");
      } else {
        reveals[i].classList.remove("active");
      }
    }
  }

  useEffect(() => {
    window.addEventListener("scroll", reveal);

    return () => {
      window.removeEventListener("scroll", reveal);
    };
  }, []);

  return (
    <div className="content page-container bg-black text-white">
      <div className="page-container">
        <Head>
          <title>Kevin Salmeron</title>
          <meta name="description" content="Generated by Kevin Salmeron" />
          <link rel="icon" href="/favicon.ico" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
          />
        </Head>

        <main className="bg-black text-white px-4 md:px-10 lg:px-20 dark:bg-gray-900">
          <div className="mb-10">
            <Navbar />
          </div>

          <div className="text-center p-10 mb-2">
            <div className="md:flex md:justify-between">
              <div className="w-full md:w-1/2 slide-in-element mt-2">
                <h2
                  style={{
                    fontWeight: "bold",
                    backgroundImage:
                      "linear-gradient(to right, #0074D9, #33ADFF)",
                    WebkitBackgroundClip: "text",
                    color: "white",
                    fontSize: "6rem",
                  }}
                  className="text-4xl md:text-7xl py-2 font-medium"
                >
                  Portfolio
                </h2>
              </div>
              <div className="w-full md:w-1/2 slide-in-element mt-2 pl-0 md:pl-8">
                <h2
                  style={{
                    fontWeight: "bold",
                    color: "white",
                    fontSize: "2.5rem",
                  }}
                  className="text-xl md:text-4xl py-2 font-medium"
                >
                  by
                  <br /> Kevin Salmeron.
                </h2>
              </div>
            </div>
          </div>

          <div className="pictures flex flex-wrap justify-center mb-10">
            <div className="p-2">
                <Image
                  src={woods2}
                  alt="woods"
                  className="image1"
                  id="image1"
                  placeholder="blur"
                  loading="lazy"
                />
            </div>
            <div className="p-2">
                <Image
                  src={city}
                  alt="city"
                  className="image2"
                  id="image2"
                  placeholder="blur"
                  loading="lazy"
                />
            </div>
            <div className="p-2">
                <Image
                  src={museum2}
                  alt="museum"
                  className="image3"
                  id="image3"
                  placeholder="blur"
                  loading="lazy"
                />
            </div>
            <div className="p-2">
                <Image
                  src={needle2}
                  alt="needle"
                  className="image4"
                  id="image4"
                  placeholder="blur"
                  loading="lazy"
                />
            </div>
          </div>

          <div className="mb-10">
            <AboutMe />
          </div>
          <section className="flex flex-col items-center mb-10 bg-black text-white w-full m-0 mt-18">
            <div
              id="projects"
              name="projects"
              className="text-5xl flex justify-center py-9 text-white-600 container reveal fade-right"
            >
              <p className="alfa-slab-one text-6xl md:text-7xl mt-8">Projects</p>
            </div>
            <div className="w-full mt-12 mb-10 text-center">
              <ImageSlider slides={slides} />
            </div>
          </section>
          <section
            id="skills"
            name="skills"
            className="flex flex-col items-center mb-10 bg-black text-white"
          >
            <div>
              <Skills />
            </div>
          </section>

          <div className="flex justify-center mb-10">
            <ScrollToTop smooth />
          </div>

          <div className="container mb-10 mt-10" id="contact" name="contact">
            <Footer />
          </div>
        </main>
      </div>
    </div>
  );
}
