import * as React from 'react';
import { useState, useEffect } from "react";
import AboutMe from './AboutMe.js';
import city from '../public/city.png';
import Footer from './Footer.js';
import Head from "next/head";
import Image from "next/image";
import Link from 'next/link.js';
import ImageSlider from "./ImageSlider.js";
import museum2 from "../public/museum2.png";
import Navbar from './Navbar.js';
import needle2 from '../public/needle2.png';
import ScrollToTop from "react-scroll-to-top";
import Skills from './Skills.js';
import SkillsHover from './SkillsHover.js';
import woods2 from '../public/woods2.png';


export default function Home() {
  //open is our initial state, used to set the value of currentState for first render
  //setOpen is the state setter used to update the value of currentState
  const [open, setOpen] = useState({
    frontEnd: false,
    backEnd: false,
    programmingLanguages: false,
    systemDesignTools: false,
  });


//function to toggle the open state for a specific skill
const toggleSkillOpen = (skill) => {
  setOpen((prevOpen) => 
  ({
    //spread operator creating a copy of the previous state(prevOpen)
    ...prevOpen,
    //[skill] specifies the property 'skill' to be updated
    //!prevOpen[skill] toggles the boolean value of the specified property.If it was true, it becomes fales and vice versa
    //together it creates a new object. It takes all the properties from the prev state(prevOpen) and updates the specific skill with new value
    [skill]: !prevOpen[skill],
  }));
};


//uses the 'getElementById' method to find the HTML element with the specified 'targetId'
  //assigns the result to the variable 'targetElement'
function handleScrollTo(targetId) {
  const targetElement = document.getElementById(targetId);
  if (targetElement) {
    targetElement.scrollIntoView({ behavior: 'smooth' });
  }
}

//for projects portion
const slides= [
  {url: '/movie.png', title: "MovieMania", gitlabLink: 'https://gitlab.com/instructors2085807/movie-maniacs.git'},
  {url: '/carcar.png', title:"CarCar", gitlabLink: 'https://gitlab.com/ksalmeron1993/car-car.git' },
  {url: 'morecoming.png', title:"Default", gitlabLink: null},
];

const containerStyles = {
  width: '500px',
  height: '280px',
  margin: '0 auto',
};


//slide in effect function
function reveal() {
  //selects all elements with the class name 'reveal' in the doc. and returns a NodeList 
  var reveals = document.querySelectorAll(".reveal");

  for (var i = 0; i < reveals.length; i++) {
    //retrieves the height of the browser window
    var windowHeight = window.innerHeight;
    //getBoundingClientRect()-This is a method that returns a DOMRect object providing information about the size of an element 
    //and its position relative to the viewport.
    // It's a value in pixels that indicates how far down the element is from the top of the viewport. 
    //This value can be used to determine whether the element is currently visible on the screen.
    var elementTop = reveals[i].getBoundingClientRect().top;
    //sets threshold value for visibility, if an element is within 150 pixels from the bottom of  the viewport it's visible.
    var elementVisible = 150;

    if (elementTop < windowHeight - elementVisible) {
      reveals[i].classList.add("active");
    } else {
      reveals[i].classList.remove("active");
    }
  }
}

  // Add the scroll event listener when the component mounts
  useEffect(() => {
    window.addEventListener("scroll", reveal);

    // Cleanup: remove the event listener when the component unmounts
    return () => {
      window.removeEventListener("scroll", reveal);
    };
  }, []); // The blur dependency array ensures the effect runs only once

  return (
    <div className="page-container bg-black text-white">
      <div className='page-container'>
      <Head>
        <title>Kevin Salmeron</title>
        <meta name="description" content="Generated by Kevin Salmeron" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
      <main className="bg-black text-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <div>
          <Navbar />
        </div>
    
      <div className="text-center p-10">
      <div className="text-left md:flex md:justify-between">
      <div className="md: w-1/2 slide-in-element mt-2">
        <h2 style={{ fontWeight: 'bold', backgroundImage: 'linear-gradient(to right, #0074D9, #33ADFF)', 
        WebkitBackgroundClip: 'text', color: 'white' }} className="text-7xl py-2 font-medium md:text-8xl">
          Portfolio
        </h2>
      </div>
      <div className="md:w-1/2 slide-in-element mt-2" style={{paddingLeft:'30px'}}>
        <h2 style={{ fontWeight: 'bold', color: 'white'}} className="text-xl py-2 font-medium md:text-5xl"> by 
        <br/> Kevin Salmeron.
        </h2>
      </div>
      </div>
      </div>
      <div className="row mt-2">
      <div className="column ">
        <Link href={'../public/woods2.png'} as={'image'}>
        <Image src={woods2} alt="woods" className="image1" id="image1" priority={true} placeholder='blur' as='image' defer/>
        </Link>
      </div>
      <div className="column">
        <Link href={'../public/city.png'} as={'image'}>
        <Image src={city} alt="city" className="image2" id="image2" priority={true} placeholder='blur' as='image' defer/>
        </Link>
      </div>
      <div className="column">
        <Link href={"../public/museum2.png"} as={'image'}>
        <Image src={museum2} alt="museum" className="image3" id="image3" priority={true} placeholder='blur' as='image' defer />
        </Link>
      </div>
      <div className="column">
        <Link href={'../public/needle2.png'} as={'image'}>
        <Image src={needle2} alt="needle" className="image4" id='image4' priority={true} placeholder='blur' as='image' defer/>
        </Link>
      </div>
      </div>
      <div style={{marginBottom: '-280px'}}>
        <AboutMe />
      </div>
    </main>

    <section className='flex flex-col items-center mt-5 bg-black text-white'>
      <div style={{marginTop: '20px'}}>
        <Skills />
      </div>
      <div style={{ marginTop: '-250px', marginBottom:'100px' }}>
        <SkillsHover />
      </div>
    </section>

    <section className='flex flex-col items-center mt-5 bg-black text-white' style={{width: '100%', margin: 0}}>
      <div id="projects" name="projects" className="text-5xl flex justify-center py-9 text-white-600 container reveal fade-right" >
      <p className="alfa-slab-one" style={{ fontSize: '90px' }}>Projects</p>      
      </div>
        <div style={{containerStyles, width: '100%', marginTop: '50px', marginBottom: '100px'}}className="text-center">
        <ImageSlider slides={slides} />
      </div>
    </section>
    <div>
      <div style={{ marginTop: "0vh"}} />
      <ScrollToTop smooth />
      </div>
    </div>
    <div style={{ marginTop: '300px'}}className="container" id="contact" name="contact">
      <Footer /> 
    </div>
   </div>
)};